# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows 
julia:
  - 1.5
  - nightly
notifications:
  email: false
git:
  depth: 99999999

after_script:
  - julia -e 'using Pkg, VCFTools; cd(joinpath(dirname(pathof(VCFTools)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.5
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using VCFTools; include(joinpath(dirname(pathof(VCFTools)), "..", "docs", "make.jl"))'
      after_success: skip
