# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email:
    on_success: change
    on_failure: always
  recipients:
    - huazhou@ucla.edu
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("VCFTools"); Pkg.test("VCFTools"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("VCFTools")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("VCFTools")); include(joinpath("docs", "make.jl"))'
