# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email:
    on_success: change
    on_failure: always
  recipients:
    - huazhou@ucla.edu

before_script: # install dependent unregistered packages
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.add([PackageSpec(url="https://github.com/biona001/VCFTools.jl")]);'

after_script:
  - julia -e 'using Pkg, VCFTools; cd(joinpath(dirname(pathof(VCFTools)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using VCFTools; include(joinpath(dirname(pathof(VCFTools)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip
