site_name:        VCFTools.jl
repo_url:         https://github.com/OpenMendel/VCFTools.jl
site_description: Utilities for handling VCF files
site_author:      Hua Zhou

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Manual:
  - VCF summary: summaryinfo.md
  - Filter data fields: filter.md
  - Convert GT data to numeric arrays:: convert.md
  - Match markers in two VCF: conformgt.md
- API: api.md
